plugins {
    id 'com.android.application'
    id 'kotlin-android'
}

android {
    namespace 'com.bmiapp.bmi_calculator'
    compileSdk 34

    defaultConfig {
        applicationId 'com.bmiapp.bmi_calculator'
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName '1.0.0'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.debug  // Replace with your release signingConfig before publishing
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
}
